### ISSUE TITLE
feature/mobile-profile-details

### ISSUE THREAD

**Issue by JessyRiordan** [MStaehling/TIY-Github#6]
Profile Details:
- [x] Left Side: 
  - [x] Image of Octocat
- [x] Right Side (in order from top to bottom):
  - [x] Header tag with name: larger font, default color
  - [x] Username: grey, smaller font
  - [x] Company: [icon](https://octicons.github.com/icon/organization/) is grey, text default color
  - [x] Location: [icon](https://octicons.github.com/icon/location/) is grey, text default color
  - [x] Email: [icon](https://octicons.github.com/icon/mail/) is grey, link to email
  - [x] url: [icon](https://octicons.github.com/icon/link/) is grey, link to website

![octocat_feature_profile_details](https://cloud.githubusercontent.com/assets/12103371/8025059/da9fef68-0d16-11e5-80aa-7e9b79c13475.png)

**Comment by MStaehling** [comment]
because of my addon my text can't be black.....so instead of saying the text is black say the text is the default color.......I have a black background. If I made my text black I wouldn't be able to see any of it. @jessyriordan

**Comment by JessyRiordan** [comment]
edited the issue....

**Comment by MStaehling** [comment]
@JessyRiordan is that a header tag or heading tag.....can have only 1 header tag
